---
kind: Namespace
apiVersion: v1
metadata: 
  name: daq
  labels:
    name: daq

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc1
  namespace: daq
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1k
  storageClassName: local-path
  
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-1
  namespace: daq
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - sleep
    - "3600"
    volumeMounts:
    - name: storage
      mountPath: /mnt/storage
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: pvc1
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-2
  namespace: daq
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - sleep
    - "3600"
    volumeMounts:
    - name: storage
      mountPath: /mnt/storage
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: pvc1

